import jsPDF from "jspdf";

// Cloover brand — light theme for PDF
const INDIGO = "#3535F3";
const INDIGO_LIGHT = "#4747F5";
const PAGE_BG = "#ffffff";
const CARD_BG = "#f8f9fb";
const TEXT_PRIMARY = "#0f172a";
const TEXT_SECONDARY = "#334155";
const TEXT_MUTED = "#64748b";

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

interface ReportData {
  customer_summary?: {
    postcode?: string;
    product_interest?: string;
    budget_band?: string;
    customer_goal?: string;
    estimated_profile?: string;
  };
  market_context?: { summary?: string; relevance_signal?: string };
  recommended_packages?: {
    name: string;
    system: string;
    capex: string;
    annual_savings: string;
    fit_reason?: string;
    target_customer?: string;
  }[];
  financing_options?: {
    type: string;
    monthly_payment: string;
    total_cost: string;
    fit_reason?: string;
    recommended?: boolean;
  }[];
  ai_summary?: string;
  best_package?: string;
  best_package_details?: { fit_reason?: string; sales_pitch?: string };
  recommended_financing?: { type?: string; fit_reason?: string };
  installer_pitch?: {
    recommended_opening?: string;
    likely_objection?: string;
    sales_focus?: string;
  };
  confidence?: number;
  assumptions?: string[];
}

function addPage(doc: jsPDF) {
  doc.addPage();
  // Dark background
  doc.setFillColor(PAGE_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
}

function drawCard(doc: jsPDF, x: number, y: number, w: number, h: number, highlight = false) {
  doc.setFillColor(highlight ? "#eeeeff" : CARD_BG);
  doc.roundedRect(x, y, w, h, 4, 4, "F");
  if (highlight) {
    doc.setDrawColor(INDIGO);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, y, w, h, 4, 4, "S");
  } else {
    doc.setDrawColor("#e2e8f0");
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, w, h, 4, 4, "S");
  }
}

function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth);
}

export function generateReport(report: ReportData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ─── PAGE 1: Cover ───────────────────────────────────────────
  doc.setFillColor(PAGE_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  // Accent bar
  doc.setFillColor(INDIGO);
  doc.rect(0, 0, PAGE_W, 4, "F");

  // Logo area
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(TEXT_PRIMARY);
  doc.text("Cloover", MARGIN, 40);

  doc.setFontSize(12);
  doc.setTextColor(INDIGO_LIGHT);
  doc.text("AI Sales Coach Report", MARGIN, 50);

  // Title
  doc.setFontSize(32);
  doc.setTextColor(TEXT_PRIMARY);
  doc.text("Sales Briefing", MARGIN, 85);

  doc.setFontSize(14);
  doc.setTextColor(TEXT_SECONDARY);
  const interest = report.customer_summary?.product_interest || "Energy Solutions";
  doc.text(`${interest} — Personalized Recommendation`, MARGIN, 96);

  // Customer card
  const custY = 115;
  drawCard(doc, MARGIN, custY, CONTENT_W, 55);

  doc.setFontSize(10);
  doc.setTextColor(TEXT_MUTED);
  doc.text("CUSTOMER OVERVIEW", MARGIN + 8, custY + 10);

  doc.setFontSize(11);
  doc.setTextColor(TEXT_PRIMARY);
  const profile = report.customer_summary?.estimated_profile || "—";
  const profileLines = wrapText(doc, profile, CONTENT_W - 16);
  doc.text(profileLines, MARGIN + 8, custY + 20);

  doc.setFontSize(9);
  doc.setTextColor(TEXT_SECONDARY);
  const details = [
    `Postcode: ${report.customer_summary?.postcode || "—"}`,
    `Interest: ${report.customer_summary?.product_interest || "—"}`,
    `Budget: ${report.customer_summary?.budget_band || "—"}`,
    `Goal: ${report.customer_summary?.customer_goal || "—"}`,
  ];
  doc.text(details, MARGIN + 8, custY + 36);

  // AI Summary
  const sumY = 185;
  drawCard(doc, MARGIN, sumY, CONTENT_W, 45, true);
  doc.setFontSize(10);
  doc.setTextColor(INDIGO_LIGHT);
  doc.text("AI SUMMARY", MARGIN + 8, sumY + 10);
  doc.setFontSize(10);
  doc.setTextColor(TEXT_PRIMARY);
  const sumLines = wrapText(doc, report.ai_summary || "No summary available.", CONTENT_W - 16);
  doc.text(sumLines.slice(0, 8), MARGIN + 8, sumY + 18);

  // Confidence + Best package footer
  doc.setFontSize(9);
  doc.setTextColor(TEXT_MUTED);
  doc.text(`Confidence: ${report.confidence ?? 0}/100`, MARGIN, 250);
  doc.text(`Best Package: ${report.best_package || "—"}`, MARGIN + 80, 250);
  doc.text(`Generated by Cleo — Cloover AI Sales Coach`, MARGIN, 285);

  // ─── PAGE 2: Market Context + Packages ───────────────────────
  addPage(doc);
  let y = 16;

  // Accent bar
  doc.setFillColor(INDIGO);
  doc.rect(0, 0, PAGE_W, 3, "F");

  // Market Context
  doc.setFontSize(14);
  doc.setTextColor(TEXT_PRIMARY);
  doc.text("Market & Regulatory Context", MARGIN, y + 10);
  y += 16;

  drawCard(doc, MARGIN, y, CONTENT_W, 50);
  doc.setFontSize(9);
  doc.setTextColor(TEXT_SECONDARY);
  const signal = report.market_context?.relevance_signal || "Medium";
  doc.text(`Relevance: ${signal}`, MARGIN + 8, y + 9);
  doc.setFontSize(10);
  doc.setTextColor(TEXT_PRIMARY);
  const mktLines = wrapText(doc, report.market_context?.summary || "No market data.", CONTENT_W - 16);
  doc.text(mktLines.slice(0, 10), MARGIN + 8, y + 17);
  y += 58;

  // Recommended Packages
  doc.setFontSize(14);
  doc.setTextColor(TEXT_PRIMARY);
  doc.text("Recommended Packages", MARGIN, y);
  y += 8;

  const packages = report.recommended_packages || [];
  const colW = (CONTENT_W - 8) / 3;

  // Package cards side by side
  for (let i = 0; i < Math.min(packages.length, 3); i++) {
    const pkg = packages[i]!;
    const px = MARGIN + i * (colW + 4);
    const isBest = pkg.name === report.best_package;
    drawCard(doc, px, y, colW, 80, isBest);

    let py = y + 8;
    // Name
    doc.setFontSize(11);
    doc.setTextColor(isBest ? INDIGO_LIGHT : TEXT_PRIMARY);
    doc.text(pkg.name, px + 6, py);
    if (isBest) {
      doc.setFontSize(7);
      doc.setTextColor(INDIGO);
      doc.text("BEST FIT", px + colW - 22, py);
    }
    py += 7;

    // System
    doc.setFontSize(8);
    doc.setTextColor(TEXT_SECONDARY);
    const sysLines = wrapText(doc, pkg.system, colW - 12);
    doc.text(sysLines.slice(0, 3), px + 6, py);
    py += sysLines.slice(0, 3).length * 3.5 + 4;

    // Capex
    doc.setFontSize(7);
    doc.setTextColor(TEXT_MUTED);
    doc.text("CAPEX", px + 6, py);
    doc.setFontSize(13);
    doc.setTextColor(TEXT_PRIMARY);
    doc.text(`€${Number(pkg.capex).toLocaleString("de-DE")}`, px + 6, py + 6);
    py += 12;

    // Savings
    doc.setFontSize(7);
    doc.setTextColor(TEXT_MUTED);
    doc.text("ANNUAL SAVINGS", px + 6, py);
    doc.setFontSize(11);
    doc.setTextColor(INDIGO_LIGHT);
    doc.text(`€${Number(pkg.annual_savings).toLocaleString("de-DE")}/yr`, px + 6, py + 5);
    py += 10;

    // Fit reason
    if (pkg.fit_reason) {
      doc.setFontSize(7);
      doc.setTextColor(TEXT_SECONDARY);
      const fitLines = wrapText(doc, pkg.fit_reason, colW - 12);
      doc.text(fitLines.slice(0, 2), px + 6, py);
    }
  }

  y += 90;

  // ─── PAGE 3: Financing + Pitch ───────────────────────────────
  if (y > 220) {
    addPage(doc);
    y = 16;
    doc.setFillColor(INDIGO);
    doc.rect(0, 0, PAGE_W, 3, "F");
  }

  // Financing Options
  doc.setFontSize(14);
  doc.setTextColor(TEXT_PRIMARY);
  doc.text("Financing Options", MARGIN, y);
  y += 8;

  const finOptions = report.financing_options || [];
  for (let i = 0; i < Math.min(finOptions.length, 3); i++) {
    const fin = finOptions[i]!;
    const fx = MARGIN + i * (colW + 4);
    drawCard(doc, fx, y, colW, 50, fin.recommended);

    let fy = y + 8;
    doc.setFontSize(10);
    doc.setTextColor(fin.recommended ? INDIGO_LIGHT : TEXT_PRIMARY);
    doc.text(fin.type, fx + 6, fy);
    if (fin.recommended) {
      doc.setFontSize(7);
      doc.setTextColor(INDIGO);
      doc.text("RECOMMENDED", fx + colW - 30, fy);
    }
    fy += 8;

    doc.setFontSize(7);
    doc.setTextColor(TEXT_MUTED);
    doc.text("MONTHLY", fx + 6, fy);
    doc.setFontSize(12);
    doc.setTextColor(TEXT_PRIMARY);
    doc.text(`€${fin.monthly_payment}`, fx + 6, fy + 5);
    fy += 10;

    doc.setFontSize(7);
    doc.setTextColor(TEXT_MUTED);
    doc.text("TOTAL COST", fx + 6, fy);
    doc.setFontSize(10);
    doc.setTextColor(TEXT_SECONDARY);
    doc.text(`€${Number(fin.total_cost).toLocaleString("de-DE")}`, fx + 6, fy + 5);
  }

  y += 60;

  // Installer Pitch Guidance
  if (y > 240) {
    addPage(doc);
    y = 16;
    doc.setFillColor(INDIGO);
    doc.rect(0, 0, PAGE_W, 3, "F");
  }

  doc.setFontSize(14);
  doc.setTextColor(TEXT_PRIMARY);
  doc.text("Installer Pitch Guidance", MARGIN, y);
  y += 8;

  drawCard(doc, MARGIN, y, CONTENT_W, 65);
  let py = y + 10;

  const pitchItems = [
    { label: "RECOMMENDED OPENING", value: report.installer_pitch?.recommended_opening },
    { label: "LIKELY OBJECTION", value: report.installer_pitch?.likely_objection },
    { label: "SALES FOCUS", value: report.installer_pitch?.sales_focus },
  ];

  for (const item of pitchItems) {
    doc.setFontSize(7);
    doc.setTextColor(INDIGO_LIGHT);
    doc.text(item.label, MARGIN + 8, py);
    py += 4;
    doc.setFontSize(9);
    doc.setTextColor(TEXT_PRIMARY);
    const lines = wrapText(doc, item.value || "—", CONTENT_W - 16);
    doc.text(lines.slice(0, 2), MARGIN + 8, py);
    py += lines.slice(0, 2).length * 4 + 4;
  }

  y = py + 10;

  // Best Package Details
  if (report.best_package_details) {
    if (y > 250) {
      addPage(doc);
      y = 16;
      doc.setFillColor(INDIGO);
      doc.rect(0, 0, PAGE_W, 3, "F");
    }

    drawCard(doc, MARGIN, y, CONTENT_W, 35, true);
    doc.setFontSize(7);
    doc.setTextColor(INDIGO_LIGHT);
    doc.text("BEST PACKAGE — SALES PITCH", MARGIN + 8, y + 9);
    doc.setFontSize(10);
    doc.setTextColor(TEXT_PRIMARY);
    const pitchLines = wrapText(doc, report.best_package_details.sales_pitch || "—", CONTENT_W - 16);
    doc.text(pitchLines.slice(0, 4), MARGIN + 8, y + 16);
  }

  // Assumptions on last page
  if (report.assumptions?.length) {
    y += 45;
    if (y > 260) {
      addPage(doc);
      y = 16;
      doc.setFillColor(INDIGO);
      doc.rect(0, 0, PAGE_W, 3, "F");
    }
    doc.setFontSize(9);
    doc.setTextColor(TEXT_MUTED);
    doc.text("Assumptions:", MARGIN, y);
    y += 5;
    doc.setFontSize(8);
    for (const a of report.assumptions.slice(0, 6)) {
      doc.text(`• ${a}`, MARGIN + 4, y);
      y += 4;
    }
  }

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(TEXT_MUTED);
  doc.text("Generated by Cleo — Cloover AI Sales Coach", MARGIN, PAGE_H - 10);
  doc.text(new Date().toLocaleDateString("de-DE"), PAGE_W - MARGIN - 25, PAGE_H - 10);

  // Save
  const name = report.customer_summary?.postcode || "report";
  doc.save(`Cloover_Sales_Report_${name}.pdf`);
}
